[package]
name = "fastcdc"
version = "1.0.6"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "FastCDC (content defined chunking) in pure Rust."
repository = "https://github.com/nlfiedler/fastcdc-rs"
readme = "README.md"
keywords = ["cdc", "chunking"]
license = "MIT"
exclude = [
    "TODO.org",
    "test/*",
]

[dependencies]
memmap = "0.7.0"

[dev-dependencies]
crypto-hash = "0.3.4"
clap = "3.0.5"
